meta_product_name: "Plantis"
meta_title: "Plantis | Because your plants are worth it"
meta_description: "Plantis helps you look after your house plants by reminding you
when each plant is thirsty."
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@project-plantis"   # required for Twitter Cards